### ISSUE TITLE
Why am I unable to uninstall it?

### ISSUE THREAD

**Issue by yaelber** [yitzchak/linter-spell#17]
I click the button but nothing happens

**Comment by yitzchak** [comment]
After you uninstall and restart all atom windows do you see it in the installed package list?

**Comment by yaelber** [comment]
All good. I didn't restart it. Thanks!

**Comment by yitzchak** [comment]
It's probably still a bug, but at least your install is clean. Thanks for reporting!

**Comment by yitzchak** [comment]
This looks like a bug in Atom <1.9 per atom/atom#11464
