### ISSUE TITLE
Unable to find Dictionary en-us 

### ISSUE THREAD

**Issue by Subh94** [yitzchak/linter-spell#22]
When i enable this in atom i am getting error "Unable to find Dictionary en-us " any help will be appreciated.

**Comment by yitzchak** [comment]
Are you using hunspell or aspell? If you are using hunspell what is the output of

``` sh
hunspell -D
```

or

``` sh
aspell dicts
```

for aspell?

**Comment by Subh94** [comment]
After running "aspell dicts" on my system

en
en-variant_0
en-variant_1
en-variant_2
en-w_accents
en-wo_accents
en_CA
en_CA-variant_0
en_CA-variant_1
en_CA-w_accents
en_CA-wo_accents
en_GB
en_GB-ise
en_GB-ise-w_accents
en_GB-ise-wo_accents
en_GB-ize
en_GB-ize-w_accents
en_GB-ize-wo_accents
en_GB-variant_0
en_GB-variant_1
en_GB-w_accents
en_GB-wo_accents
en_US
en_US-variant_0
en_US-variant_1
en_US-w_accents
en_US-wo_accents

**Comment by yitzchak** [comment]
Please try upgrading to v0.10.3

**Comment by yitzchak** [comment]
I think this is fixed in >v0.10.3

**Comment by yitzchak** [comment]
Closing assuming that this is fixed. I will reopen if it is not.
