### ISSUE TITLE
Backwards cycling through suggestions

### ISSUE THREAD

**Issue by oscarlevin** [yitzchak/linter-spell#23]
I'm not sure if this is an issue for linter-spell, intentions, or linter, but upon hitting alt+enter on a misspelled word, the up and down arrows cycle through the options backwards.  Down arrow highlights the entry above the currently highlighted one, up arrow highlights below.

**Comment by yitzchak** [comment]
I think this is a bug in intentions. I rolled back to v1.0.5 from v1.1.0 and it works fine. They changed to `core:move-up` in v1.1.0.

**Comment by oscarlevin** [comment]
Interesting.  I see you beat me to posting the issue there.  Thanks for looking into this.

**Comment by yitzchak** [comment]
@steelbrain posted the fix in v1.1.1
