### ISSUE TITLE
Seems not to work

### ISSUE THREAD

**Issue by EdwinHuijsing** [yitzchak/linter-spell#24]
Hallo,

I just installed the add-in, without any problems.
- Created a new documet (<kbd>CTRL</kbd>+<kbd>N</kbd>)
- <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>L</kbd>
- copied text from https://nl.wikipedia.org/wiki/Nederland
- pressed <kbd>ALT</kbd>+<kbd>Y</kbd> and selected nl-NL

But the spell check still underlined most of it, like it uses en-US. The same if de-DE with the link https://de.wikipedia.org/wiki/Nederland

I have Hunspell installed, us it with LibreOffice.
OS: Linux

From the devTool console:
/home/<name>/.atom/packages/linter-spell/lib/main.js:37
`All dependencies installed, good to go`

/home/<name>/.atom/packages/linter-spell/lib/spell.js:67

```
Array[1]:
  "en-US"
```

Did I miss something? Any setting that i must change?

Thanks for the effort.
Edwin

**Comment by yitzchak** [comment]
After you selected nl-NL did the language update in the status bar?

**Comment by EdwinHuijsing** [comment]
Yes the language changed.

That's something I also tried, open new tab, past content  and then change language in the status bar.
Result is the same.

**Comment by yitzchak** [comment]
What is the output of the following?

``` bash
hunspell -D
```

**Comment by EdwinHuijsing** [comment]
``` bash
SEARCH PATH:
.::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/usr/share/dict/ooo:/Library/Spelling:/home/edwin/.openoffice.org/3/user/wordbook:.openoffice.org2/user/wordbook:.openoffice.org2.0/user/wordbook:Library/Spelling:/opt/openoffice.org/basis3.0/share/dict/ooo:/usr/lib/openoffice.org/basis3.0/share/dict/ooo:/opt/openoffice.org2.4/share/dict/ooo:/usr/lib/openoffice.org2.4/share/dict/ooo:/opt/openoffice.org2.3/share/dict/ooo:/usr/lib/openoffice.org2.3/share/dict/ooo:/opt/openoffice.org2.2/share/dict/ooo:/usr/lib/openoffice.org2.2/share/dict/ooo:/opt/openoffice.org2.1/share/dict/ooo:/usr/lib/openoffice.org2.1/share/dict/ooo:/opt/openoffice.org2.0/share/dict/ooo:/usr/lib/openoffice.org2.0/share/dict/ooo
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/usr/share/hunspell/de_CH
/usr/share/hunspell/en_CA
/usr/share/hunspell/en_US
/usr/share/hunspell/de_DE
/usr/share/hunspell/de_AT
/usr/share/hunspell/en_GB
/usr/share/hunspell/nl_NL
/usr/share/myspell/de_CH
/usr/share/myspell/en_CA
/usr/share/myspell/en_US
/usr/share/myspell/de_DE
/usr/share/myspell/de_AT
/usr/share/myspell/en_GB
/usr/share/myspell/nl_NL
LOADED DICTIONARY:
/usr/share/hunspell/en_US.aff
/usr/share/hunspell/en_US.dic
Hunspell 1.3.3
```

**Comment by yitzchak** [comment]
Is the `spell-check` package enabled?

**Comment by EdwinHuijsing** [comment]
Yes, atom `spell-check` is enabled

**Comment by yitzchak** [comment]
`spell-check` does not understand non English documents. Try disabling it, please.

**Comment by EdwinHuijsing** [comment]
I have disabled the package, but not when i past text from https://nl.wikipedia.org/wiki/Nederland. No check is down, the dutch text is now valid in en-US, nl-NL, de-DE.

**Comment by yitzchak** [comment]
Okay, I probably wasn't clear before. Can you check to make sure that `linter-spell` is _enabled_ and `spell-check` is _disabled._ `spell-check` is a core package and will be in the "Core Packages" list.

**Comment by EdwinHuijsing** [comment]
It is already as you state
`linter-spell` is enabled
atom `spell-check` is disabled

**Comment by yitzchak** [comment]
Okay. Well try restarting atom just in case. If that does not work, I'll have to think about it some more since I was not able to replicate on Arch.

**Comment by EdwinHuijsing** [comment]
I have done that already, with result. 

I have done some testing HTH

I have disabled all packages except for:
- Intentions
- linter
- linter-spell

Two this if found
1 If i save the dutch text to file, the spelling validation becomes active
2 After reopening
- close the file open it
- open it
- save it

I am still looking for other options to test
- press spacebar
  it has to be in this order

**Comment by yitzchak** [comment]
I think I know what it is. What version of atom do you have?

**Comment by EdwinHuijsing** [comment]
1.9.8

**Comment by yitzchak** [comment]
I guess not. There was an package activation bug, but that was fixed in 1.9.6

**Comment by EdwinHuijsing** [comment]
Can you write some tests (spec) that i can run, it should contain the language code.
If possible something like
  For Aspell or Hunspell could be taken from the settings.
  If language exists then run test else add/show skip message
  Test: is linter active, are there error found, is language set, ...
I don't know it it's posible, but if it is this could provide the information need.

I have stepped through the code, but I don't find the place where the check is call or i don't understand it. JavaScript is very new to me. But i can read it because have have used PHP and C#.
If I know where to look i will check it.

Let me know what the options are, and i will try them tomorrow.

**Comment by yitzchak** [comment]
May take a bit to get some together.  

What does `locale` report for you?

**Comment by EdwinHuijsing** [comment]
``` bash
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

**Comment by yitzchak** [comment]
Can you try the following? FIrst:
1. <kbd>Ctrl</kbd>+<kbd>N</kbd>
2. Paste
3. <kbd>Alt</kbd>+<kbd>Y</kbd> and select nl-NL
4. <kbd>Ctrl</kbd>+<kbd>S</kbd> and save as text file.

For me the spelling errors show in the linter pane at the bottom of atom, but sometimes the errors are not underlined.

Second:
1. Close the file
2. Close and reopen atom
3. Open the file
4. <kbd>Ctrl</kbd>+<kbd>S</kbd>

**Comment by EdwinHuijsing** [comment]
I run the test more then once, the outcome did not change.

**Test one new file**
- after changing the language no error found
- after save 3 error found, added yellow dots in gutter, underlined the errors

**Test two op file**
- Language detected en-US
- errors 177, added yellow dots in gutter, underlined the errors

**_linter-spell version 0.11.0**_

**Comment by yitzchak** [comment]
On the second test please try changing the language then saving.

Also please note that linter-spell does not do "on-the-fly" spell checking. It **only** spell checks after save.

**Comment by EdwinHuijsing** [comment]
Thanks, it works.
In short, i missed the saving part.

Long version with a note and question:

> Also please note that linter-spell does not do "on-the-fly" spell checking. It only spell checks after save.
> I can't remember seeing/reading that i should save the document it, but yes after saving the works

Most of the time i read first line and the check the short-cuts after installing. Also the spell-checks that i am using (Office, browser, ...), do on-the-fly checks. The linters that I work with in atom, also check on the fly. 
So I think assuming and scanning/quick-reading the text made me miss the saving information.

Maybe you should ad it to the first line, because it tells the users what it does. something like

> Multilingual grammar-specific spell checking on save for Atom and linter using Ispell compatible interface such as GNU Aspell or Hunspell.

Are there plans to check on the fly?

**Comment by yitzchak** [comment]
Yes, I want it to eventually support on the fly checking. It will probably be difficult to do though since linter does not keep track of incremental changes in the source file and spell checking is slow process.

I am going to leave this issue open and flag it as an enhancement. I'll see if I can figure out how to spell check upon language selection.

**Comment by EdwinHuijsing** [comment]
The [php-integrator-linter](https://github.com/Gert-dev/php-integrator-linter) checks on the fly, maybe you check how it works there.

**Comment by yitzchak** [comment]
Split this into #26 and #27
