### ISSUE TITLE
updateDictionaries() in language-manager.js fail  in hunspell case with non english interface

### ISSUE THREAD

**Issue by fndercole** [yitzchak/linter-spell#25]
On line 177 in `linter-spell/lib/language-manager.js` you match «AVAILABLE DICTIONARIES» string. 

```
 if (line.match(/AVAILABLE DICTIONARIES/)) {
```

But, in my installation, hunspell interface was translated in spanish, so this line must be replaced by 

```
if (line.match(/DICCIONARIOS DISPONIBLES/)) {
```

I change this line after each linter-spell update, to achieve the dictionaries list query.

I tried to identify an universal way to fix this, but I can't found it. 

I hope that you can..

Thanks, Best!

Favio

**Comment by yitzchak** [comment]
Thanks for reporting. I'll put in a translation table probably.

**Comment by yitzchak** [comment]
Try upgrading to v0.11.1

**Comment by fndercole** [comment]
Now works!, thanks.

**Comment by yitzchak** [comment]
Awesome.
