### ISSUE TITLE
Support on the fly linting

### ISSUE THREAD

**Issue by yitzchak** [yitzchak/linter-spell#26]
As mentioned in #24

**Comment by Aerijo** [comment]
Can this be done at least every time a spelling error is corrected? Currently it still marks the corrected word as mispelt until the next save, which is annoying.

**Comment by Aerijo** [comment]
One possibility, to emulate this, is to spell check the previous word immediately when a space is entered. I don't know how to go about doing this (is there a key press event?), but it seems reasonable to me. It means the entire file doesn't get checked repeatedly, and users can immediately tell if new words are misspelt.

Alternatively, [`onDidStopChanging`](https://atom.io/docs/api/v1.23.1/TextBuffer#instance-onDidStopChanging) looks like a promising way to time the spell check. It might not work if the user types really quickly, but spell checking the changed text range should be small enough to be easy, and quick enough to appear to be 'on the fly'.

**Comment by AlexWayfer** [comment]
> @yitzchak closed this 1 hour ago

Why?

**Comment by AlexWayfer** [comment]
@yitzchak, please, don't close issues without explanation. I'm still interested in this.

**Comment by yitzchak** [comment]
@AlexWayfer This issue is 4 years old and was really a note to myself when I maintained this package. There hasn't been any activity in this project for two years. If you want this feature then its probably up to you.

**Comment by AlexWayfer** [comment]
> There hasn't been any activity in this project for two years. If you want this feature then its probably up to you.

OK, but I don't see a reason for the issue closing — it's still an issue, it's still here.
