### ISSUE TITLE
Doesn't work properly for in `vim-mode` 

### ISSUE THREAD

**Issue by shemerey** [yitzchak/linter-spell#31]
@yitzchak thx for an awesome project, but I found one problem while using it in `vim-mode` I am using `vim-mode-plus` but probably it will have same problems for  `vim-mode`  too. 

For some reason, you can't add `word` into dictionary while you in normal mode. you have to be in `insert` mode to be able to add `word`. 

Might be you can point me in source code where you handle this, or this issue for `intentions`

**Comment by shemerey** [comment]
Never mind I figured it was problem with priority of keymapping for `intentions`

solve it with 

```
'atom-text-editor.vim-mode-plus.intentions-list:not(.insert-mode)':
  'enter': 'intentions:confirm'
```

**Comment by yitzchak** [comment]
Thanks for investigating! Glad you were able to solve the issue.
