### ISSUE TITLE
Setting encoding.

### ISSUE THREAD

**Issue by runar-rkmedia** [yitzchak/linter-spell#32]
I currently have a problem with running `linter-spell` for the norwegian language. The special norwegian-letters æ,ø,å seems to be making some problems, and I would guess that this is due to some encoding. I am using `aspell`, which is set to use UTF-8. encoding, and the document is also in UTF-8.  

This might not be a bug with linter-spell, but it seems to me that it is.

In the test below, the text is written correctly, but `linter-spell` thinks that it is not, with some suggestions with a circled questionmark, indicating encoding problems.

![scr 3](https://cloud.githubusercontent.com/assets/5629981/19659562/c19f9a78-9a2c-11e6-8303-4ff566e45c7c.png)

**Comment by yitzchak** [comment]
What language is selected in the status bar at the bottom right?

**Comment by runar-rkmedia** [comment]
I've tested both `nb`(Norwegian Bokmål) and `no`(Nowegian). On words that do not contain the special letters æ, ø or å, the spellchecking works great.

**Comment by yitzchak** [comment]
Okay, I have not been able to reproduce yet. What version of `linter-spell` do you have and what kind grammar is the file (plain-text, etc)?

**Comment by runar-rkmedia** [comment]
`linter-spell` is version 0.12.0. The grammar is `plain-text`, but also on `latex` I'm running  Atom 1.12.2 on macOS Sierra.

**Comment by yitzchak** [comment]
Please try upgrading to 0.12.1.

**Comment by runar-rkmedia** [comment]
Same thing happens after upgrade.

![scr_4](https://cloud.githubusercontent.com/assets/5629981/19728636/7913a4ca-9b94-11e6-96c8-15933409a1b3.png)

**Comment by yitzchak** [comment]
Try upgrading to 0.12.2. Also aspell may not like the additional en-US dictionary and you need to separate  languages with commas in the settings page.

**Comment by runar-rkmedia** [comment]
the new version works. (did not change anything else as suggested in your last comment)

Thank you so much for the update, and for a great tool.

**Comment by yitzchak** [comment]
Awesome!
