### ISSUE TITLE
Adding case-sensitive words adds `null`

### ISSUE THREAD

**Issue by StupidUselessAccount** [yitzchak/linter-spell#34]
Hello,

When I add a case-sensitive word to my LaTeX dictionary, it is added in my `config.cson` as "null" (throwing an error when used to spellcheck the document). If I look at the code in `node_modules/linter-spell-word-list/main.js`, line 63 there is a call to `addWord` with only one parameter while in the other call there are three parameters. If I replace `this.addWord('!' + text)` with `this.addWord(textEditor, languages, '!' + text)`, it seems to work.

Also, I have a side question. Perhaps I should open an "issue" for it, I'm not sure. Where is stored the "personal dictionary"? My "personal dictionary path" is empty, but registering words in it work (with Alt+enter, with the "intention" package). I cleared my `.atom` and the words were remembered. I tried to change from `aspell` to `hunspell` but the words were also remembered.

**Comment by yitzchak** [comment]
Thanks for reporting the issue and tracking down the cause. I just pushed out a patch.

Your personal dictionary path is chosen by hunspell or aspell if you do not specify one. For hunspell it is usually: `$HOME/.hunspell_default`

**Comment by StupidUselessAccount** [comment]
Thanks! It's the same for aspell, I found my words in `~/.aspell.fr.pws`.
