### ISSUE TITLE
Spell checking doesn't activate in atom 1.13.1

### ISSUE THREAD

**Issue by ghost** [yitzchak/linter-spell#42]
Linter-spell doesn't check spelling at all in Atom 1.13.1 on macOS 10.12.2. 

For reference the rest of the linter-thing work fine, chktex, for instance has no issues.

**Comment by yitzchak** [comment]
You probably need to specify the path to hunspell. `brew` doesn't put it the system path.

**Comment by X-G** [comment]
Hi yitzchak,
I'm trying to using package on Windows 7, but have issues to install hunspell. Could you share an easy way to install hunspell?
Many thanks.
