### ISSUE TITLE
Disable for some file

### ISSUE THREAD

**Issue by mariogeiger** [yitzchak/linter-spell#43]
Is there a way to diable the spell check in some particular file ?

I like the spell check in markdown files but what if I dont want it for a particular file ?

**Comment by yitzchak** [comment]
There is not a way to do this currently. I'll add it to the todo list.

**Comment by Arcanemagus** [comment]
You can do this from Linter itself:

1. Open the Command Palette
2. Run "Linter: Toggle Active Editor

_All_ linting will be disabled on that file until you close and re-open it (or run the command again). If you would like to permanently disable all linters for a specific file you can add it to the ignore list in Linter.

**Comment by yitzchak** [comment]
@Arcanemagus Awesome. Thanks for the help.
