### ISSUE TITLE
Package missing?

### ISSUE THREAD

**Issue by codemonkey800** [yitzchak/linter-spell#48]
I'm getting a 404 right now for this package. Not sure if this was intended, but here's what I'm getting as of today:

![image](https://cloud.githubusercontent.com/assets/2176050/24537525/8c991af2-1597-11e7-9580-0f5a8c82fa97.png)

**Comment by steelbrain** [comment]
Yeah I just got the same. Ping @yitzchak

**Comment by yitzchak** [comment]
@steelbrain @Arcanemagus I haven't put up a notice up yet, but I am not able to devote enough time to support this one. I have a large project that I have been working for about 4 months.

IMHO `linter-spell` and family need a full rewrite, possibly merging them all into a single package? If someone wants to adopt/fork please feel free.

**Comment by Arcanemagus** [comment]
Do you want to move the repo into the AtomLinter org? I can keep it working and help anyone interested in maintaining it.

The procedures can be found [here](https://github.com/AtomLinter/Meta/wiki/Migrating-a-repository).

**Comment by yitzchak** [comment]
@Arcanemagus Sounds good.

**Comment by Arcanemagus** [comment]
All 7 repos transferred into the org, you have explicit Admin rights on all of them, as well as a team created that allows write access to all of them, I'll try to get a (re-)release published on them later today restoring them to APM at the new location.

**Comment by yitzchak** [comment]
Awesome. Please note that `linter-spell-word-list` is a npm support package. I've added you as a collaborator.

**Comment by codemonkey800** [comment]
Wow! Glad we got this resolved 😃 I'll close this issue then.

**Comment by Arcanemagus** [comment]
v0.13.1 re-published on APM 😉 🎉
