### ISSUE TITLE
Call to hunspell failded with a code of null

### ISSUE THREAD

**Issue by stevenlis** [yitzchak/linter-spell#74]
I got the following error when launching Atom.
![snap1](https://user-images.githubusercontent.com/33796896/42718635-a3c69a20-86d8-11e8-9046-f73cbdcc9ff3.jpg)

Does this mean I have to install hunspell or something? If so, how to install it on Wins? All the instructions I found is about Mac.

Versions: 
Windows 10
Atom 1.28.2
linter-spell 0.15.0
linter-spell-latex 0.11.0

**Comment by jsg2021** [comment]
This alert happens on Atom startup every time. Its working but it seems to do something on startup to alert this.

**Comment by JackSwett** [comment]
Info to compile Hunspell from source on their GitHub. Not sure if there is an installer out there, probably is.
[https://github.com/hunspell/hunspell](https://github.com/hunspell/hunspell)

For Ubuntu users, just `apt install hunspell`, and the error goes away.

If not, change the spell-path in the settings to aspell, instead of hunspell

**Comment by NaCl222** [comment]
Use Msys2 to install Hunspell (on windows )
1.install Msys2   https://www.msys2.org/
2.install program Hunspell with Msys2
2.1 pacman -Ss Hunspell (to search the version of Hunspell)
2.2 pacman -S <package name>(may be mingw-w64-x86_64-hunspell)
Done.
It costs me a lot of time to fix the spell-checker, glad to help u~

**Comment by stevenlis** [comment]
@NaCl222 @JackSwett @jsg2021 Thanks a lot guys but I no longer use Atom.

**Comment by leviyevalex** [comment]
> Use Msys2 to install Hunspell (on windows ) 1.install Msys2 https://www.msys2.org/ 2.install program Hunspell with Msys2 2.1 pacman -Ss Hunspell (to search the version of Hunspell) 2.2 pacman -S (may be mingw-w64-x86_64-hunspell) Done. It costs me a lot of time to fix the spell-checker, glad to help u~

What is the "spell-path" that Atom wants after following these steps?
