### ISSUE TITLE
Unable to find a dictionary for Russian language

### ISSUE THREAD

**Issue by AlexWayfer** [yitzchak/linter-spell#81]
![image](https://user-images.githubusercontent.com/6510020/116901075-2ac05980-ac42-11eb-97cd-8cf81226d778.png)

Arch Linux, tried with [`hunspell-ru`](https://aur.archlinux.org/packages/hunspell-ru/) and [`hunspell-ru-aot`](https://aur.archlinux.org/packages/hunspell-ru-aot/).

**Comment by vBuresh** [comment]
It works well on my Debian 11 with settings like this:
![linter-spell-settins](https://user-images.githubusercontent.com/20504132/121654120-10319980-caa6-11eb-917d-66b68cf136d5.png)
For more information on connecting dictionaries on Arch Linux, see [atom / spellcheck README.md ] (https://github.com/atom/spell-check#arch-linux). The setting is similar to the linter-spell.

**Comment by AlexWayfer** [comment]
It turned out Arch Linux `ru` package problem, its update: https://aur.archlinux.org/packages/hunspell-ru/#comment-806056

Sorry for bothering.
